# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
# Check https://fabricmc.net/develop for the exact/latest numbers for 1.16.5 if any of these fail to resolve.
minecraft_version=1.16.5
yarn_mappings=1.16.5+build.10
loader_version=0.11.7

# Mod Properties
mod_version=1.0.0
maven_group=furgl.infinitory
archives_base_name=infinitory

# Dependencies
fabric_version=0.34.9+1.16
